###############################################################################
#        Copyright (C) 2020        Sebastian Francisco Colomar Bauza          #
#        Copyright (C) 2020        Alejandro Colomar Andrés                   #
#        SPDX-License-Identifier:  GPL-2.0-only                               #
###############################################################################

version: "3.8"

services:

    web:
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        image: nginx
        ports:
        -   80:80
        volumes:
        -   ./Web/:/usr/share/nginx/html/:ro

################################################################################
#sudo docker swarm init                                                        ;
#sudo docker stack deploy -c docker-compose-devel.yaml web-devel               ;
#sudo docker stack rm web-devel                                                ;
################################################################################
