################################################################################
##      Copyright (C) 2020        Sebastian Francisco Colomar Bauza           ##
##      Copyright (C) 2020        Alejandro Colomar Andrés                    ##
##      SPDX-License-Identifier:  GPL-2.0-only                                ##
################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
    name: www-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            service: www-svc
    template:
        metadata:
            labels:
                service: www-svc
        spec:
            containers:
            -
                image: "alejandrocolomar/www:0.16-a7-kube"
                name: www-container
                volumeMounts:
                -
                    mountPath: /usr/local/etc/nginx/nginx.conf
                    name: nginx-conf-volume
                    readOnly: true
                    subPath: nginx.conf
                -
                    mountPath: /usr/local/etc/nginx/conf.d/security-parameters.conf
                    name: nginx-confd-security-parameters-volume
                    readOnly: true
                    subPath: security-parameters.conf
                -
                    mountPath: /usr/local/etc/nginx/conf.d/server.conf
                    name: nginx-confd-server-volume
                    readOnly: true
                    subPath: server.conf
            volumes:
            -
                name: nginx-conf-volume
                configMap:
                    name: nginx-conf-cm
            -
                name: nginx-confd-security-parameters-volume
                configMap:
                    name: nginx-confd-security-parameters-cm
            -
                name: nginx-confd-server-volume
                configMap:
                    name: nginx-confd-server-cm

