################################################################################
##      Copyright (C) 2020        Sebastian Francisco Colomar Bauza           ##
##      Copyright (C) 2020        Alejandro Colomar Andrés                    ##
##      SPDX-License-Identifier:  GPL-2.0-only                                ##
################################################################################
---
apiVersion: v1
kind: Service
metadata:
    name: www
spec:
    ports:
    -
        nodePort: 32001
        port: 8080
    selector:
        service: www-svc
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: www-deploy
spec:
    replicas: 3
    selector:
        matchLabels:
            service: www-svc
    template:
        metadata:
            labels:
                service: www-svc
        spec:
            containers:
            -
                image: "alejandrocolomar/www:kube"
                name: www-container
                volumeMounts:
                -
                    mountPath: /usr/local/etc/nginx/
                    name: nginx_conf-volume
                    readOnly: true
                -
                    mountPath: /usr/local/etc/nginx/conf.d/
                    name: nginx_conf_d-volume
                    readOnly: true
            volumes:
            -
                configMap:
                    name: nginx_conf-cm
                name: nginx_conf-volume
            -
                configMap:
                    name: nginx_conf_d-cm
                name: nginx_conf_d-volume
---
