################################################################################
##      Copyright (C) 2020        Sebastian Francisco Colomar Bauza           ##
##      Copyright (C) 2020        Alejandro Colomar Andrés                    ##
##      SPDX-License-Identifier:  GPL-2.0-only                                ##
################################################################################
---
apiVersion: v1
kind: Service
metadata:
    name: www
spec:
    ports:
    -
        nodePort: 32001
        port: 8080
    selector:
        service: www_svc
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: www_deploy
spec:
    replicas: 3
    selector:
        matchLabels:
            service: www_svc
    template:
        metadata:
            labels:
                service: www_svc
        spec:
            containers:
            -
                image: "alejandrocolomar/www:kube"
                name: www_container
                volumeMounts:
                -
                    mountPath: /usr/local/etc/nginx/
                    name: nginx-conf_volume
                    readOnly: true
            volumes:
            -
                configMap:
                    name: nginx-conf_cm
                name: nginx-conf_volume
                projected:
---
