################################################################################
##      Copyright (C) 2020        Sebastian Francisco Colomar Bauza           ##
##      Copyright (C) 2020        Alejandro Colomar Andrés                    ##
##      SPDX-License-Identifier:  GPL-2.0-only                                ##
################################################################################

configs:
    etc-nginx-conf-d-security-parameters-conf-www-config:
        file: /run/configs/www/etc/nginx/conf.d/security-parameters.conf
    etc-nginx-conf-d-server-www-config:
        file: /run/configs/www/etc/nginx/conf.d/server.conf

networks:
    alejandro-colomar:

services:
    www:
        configs:
        -
            mode: 0440
            source:  etc-nginx-conf-d-security-parameters-conf-www-config
            target: /etc/nginx/conf.d/security-parameters.conf
        -
            mode: 0440
            source:  etc-nginx-conf-d-server-www-config
            target: /etc/nginx/conf.d/server.conf
        deploy:
            mode: replicated
            placement:
                constraints:
                -   node.role == worker
            replicas: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: "1g"
                reservations:
                    cpus: "0.5"
                    memory: "1g"
            restart_policy:
                condition: any
        healthcheck:
            interval: 10s
            retries: 3
            start_period: 30s
            test: curl -4s -o /dev/null -w '%{http_code}' http://localhost:8080
            timeout: 1s
        image: "docker.io/alejandrocolomar/www:0.46@sha256:f59659e57ba556dbf26910c050fe34939dfb17b3183f85ecb32f96a016c810a2"
        networks:
        -
            "alejandro-colomar"
        ports:
        -   "30001:8080"

version: "3.8"
