################################################################################
#        Copyright (C) 2020        Sebastian Francisco Colomar Bauza           #
#        Copyright (C) 2020        Alejandro Colomar Andrés                    #
#        SPDX-License-Identifier:  GPL-2.0-only                                #
################################################################################

configs:
    named:
        file: /run/configs/etc/bind/named.conf

secrets:
    forward:
        file: /run/secrets/var/bind/master/alejandro-colomar.com
    reverse:
        file: /run/secrets/var/bind/master/10.168

services:
    dns:
        configs:
        -
            mode: 0440
            source: named
            target: /etc/bind/named.conf
        deploy:
            mode: global
        image: "alejandrocolomar/www.alejandro-colomar:dns_0.8-testing_arm64v8"
        ports:
        -   "5353:53/udp"
        secrets:
        -
            mode: 0440
            source: forward
            target: var/bind/master/alejandro-colomar.com
        -
            mode: 0440
            source: reverse
            target: var/bind/master/10.168

    http:
        deploy:
            placement:
                constraints:
                -   node.role == worker
            replicas: 3
            restart_policy:
                condition: any
        image: "alejandrocolomar/www.alejandro-colomar:http_0.8-testing_arm64v8"
        ports:
        -   30001:80

version: "3.8"

################################################################################
#sudo docker swarm init                                                        ;
#sudo docker stack deploy -c etc/docker/swarm/docker-compose.arm64v8.yaml web  ;
#sudo docker stack rm web                                                      ;
################################################################################
