###############################################################################
#        Copyright (C) 2020        Sebastian Francisco Colomar Bauza          #
#        Copyright (C) 2020        Alejandro Colomar Andrés                   #
#        SPDX-License-Identifier:  GPL-2.0-only                               #
###############################################################################

version: "3.8"

services:

    web:
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        image: nginx@sha256:676b8117782d9e8c20af8e1b19356f64acc76c981f3a65c66e33a9874877892a
        ports:
        -   80:80
        volumes:
        -   ../../etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        -   ../../etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
        -   ../../share/nginx/html/:/usr/share/nginx/html/:ro
        -   ../../share/nginx/pictures/:/usr/share/nginx/pictures/:ro
        -   ../../share/nginx/downloads/:/usr/share/nginx/downloads/:ro

################################################################################
#sudo docker swarm init                                                        ;
#sudo docker stack deploy -c etc/docker/swarm/devel/web-devel.yaml web-devel              ;
#sudo docker stack rm web-devel                                                ;
################################################################################
