name: CI-push

env:
    compose: etc/docker/swarm/compose.yaml
    project: www
    tag: ci
on:
    push:
    pull_request:
jobs:
    main:
        runs-on: ubuntu-20.04
        steps:
        -
            name: git clone alx/config
            run: |
                sudo git -C /usr/local/src \
                        clone --single-branch --branch "0.2.0" \
                        http://github.com/alejandro-colomar/config.git;
        -
            name: alx/config docker
            run: sudo make -C /usr/local/src/config docker;
        -
            name: checkout
            uses: actions/checkout@v2
        -
            name: config branch
            run: |
                git config --global user.email "ci@test.com";
                git config --global user.name "ci";
                ./bin/version/release_exp.sh "${tag}";
        -
            name: docker build
            run: docker build -t "alejandrocolomar/${project}:${tag}" .;
        -
            name: docker swarm init
            run: docker swarm init --advertise-addr lo;
        -
            name: Fix swarm compose for a single machine
            run: sed -i "s/worker/manager/" "${compose}";
        -
            name: deploy
            run: sudo ./bin/containers/deploy.sh;
        -
            name: wait Up
            run: |
                while true; do
                    sleep 1;
                    docker service ls \
                    |grep '\([0-9]\)/\1' \
                        && break;
                done;
        -
            name: curl
            run: |
                while true; do
                    sleep 1;
                    curl -4s -o /dev/null -w '%{http_code}' localhost:32001 \
                    |grep 200 \
                        && break;
                done;
