name: CI-push

on:
    push:
    pull_request:
jobs:
    main:
        runs-on: ubuntu-20.04
        steps:
        -
            name: git clone alejandro-colomar/containers
            run: |
                sudo git -C /usr/local/src \
                        clone --single-branch --branch 'v0.4.1' \
                        http://github.com/alejandro-colomar/containers.git;
        -
            name: make swarm
            run: sudo make -C /usr/local/src/containers swarm;
        -
            name: checkout
            uses: actions/checkout@v2
        -
            name: git config
            run: |
                git config --global user.email 'ci@test.com';
                git config --global user.name 'ci';
        -
            name: sed
            run: sed -i 's/worker/manager/' etc/swarm/manifests/compose.yaml;
        -
            name: release_test
            run: ./bin/release_test 'ci';
        -
            name: make config
            run: make config;
        -
            name: make image
            run: |
                make image-build;
                docker image tag \
                        'alejandrocolomar/www:ci_x86_64' \
                        'alejandrocolomar/www:ci';
        -
            name: docker swarm init
            run: docker swarm init --advertise-addr lo;
        -
            name: make stack-deploy
            run: sudo make stack-deploy;
        -
            name: docker service ls
            run: |
                while true; do
                    sleep 1;
                    docker service ls \
                    |grep '\([0-9]\)/\1' \
                        && break;
                done;
        -
            name: curl
            run: |
                while true; do
                    sleep 1;
                    curl -4s -o /dev/null -w '%{http_code}' localhost:31001 \
                    |grep 200 \
                        && break;
                done;
