name: CI-push

env:
    compose: etc/swarm/manifests/compose.yaml
on:
    push:
    pull_request:
jobs:
    main:
        runs-on: ubuntu-20.04
        steps:
        -
            name: git clone alejandro-colomar/containers
            run: |
                sudo git -C /usr/local/src \
                        clone --single-branch --branch "0.4.0" \
                        http://github.com/alejandro-colomar/containers.git;
        -
            name: make swarm
            run: sudo make -C /usr/local/src/containers swarm;
        -
            name: checkout
            uses: actions/checkout@v2
        -
            name: git config
            run: |
                git config --global user.email "ci@test.com";
                git config --global user.name "ci";
        -
            name: release_unstable
            run: ./bin/release_unstable "ci";
        -
            name: make image
            run: make image;
        -
            name: docker swarm init
            run: docker swarm init --advertise-addr lo;
        -
            name: sed
            run: sed -i "s/worker/manager/" "${compose}";
        -
            name: make stack-deploy
            run: sudo make stack-deploy;
        -
            name: docker service ls
            run: |
                while true; do
                    sleep 1;
                    docker service ls \
                    |grep '\([0-9]\)/\1' \
                        && break;
                done;
        -
            name: curl
            run: |
                while true; do
                    sleep 1;
                    curl -4s -o /dev/null -w '%{http_code}' localhost:32001 \
                    |grep 200 \
                        && break;
                done;
